DROP DATABASE IF EXISTS TestDB1;
DROP DATABASE IF EXISTS TestDB2;
DROP DATABASE IF EXISTS TestDB3;

CREATE DATABASE TestDB1;
CREATE DATABASE TestDB2;
CREATE DATABASE TestDB3;

USE TestDB1;
CREATE TABLE IF NOT EXISTS Table1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    age INT
);
CREATE TABLE IF NOT EXISTS Table2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100),
    phone VARCHAR(20),
    city VARCHAR(50)
);

USE TestDB2;
CREATE TABLE IF NOT EXISTS Table1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS Table2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100),
    password_hash VARCHAR(255),
    last_login TIMESTAMP
);

USE TestDB3;
CREATE TABLE IF NOT EXISTS Table1 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(255),
    price DECIMAL(10,2),
    stock INT
);
CREATE TABLE IF NOT EXISTS Table2 (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    customer_name VARCHAR(100),
    order_date DATE
);

DROP USER IF EXISTS 'administrator1'@'%';
DROP USER IF EXISTS 'user1'@'%';
DROP USER IF EXISTS 'user2'@'%';

CREATE USER 'administrator1'@'%' IDENTIFIED BY 'Password!23';
CREATE USER 'user1'@'%' IDENTIFIED BY 'Password!23';
CREATE USER 'user2'@'%' IDENTIFIED BY 'Password!23';

GRANT ALL PRIVILEGES ON *.* TO 'administrator1'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON TestDB1.* TO 'user1'@'%';
GRANT SELECT ON TestDB2.* TO 'user1'@'%';

GRANT ALL PRIVILEGES ON TestDB2.* TO 'user2'@'%';
GRANT SELECT, INSERT, UPDATE ON TestDB3.* TO 'user2'@'%';

FLUSH PRIVILEGES;
